# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/qtDesigner/addNewWordDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddNewWordDialog(object):
    def setupUi(self, AddNewWordDialog):
        AddNewWordDialog.setObjectName("AddNewWordDialog")
        AddNewWordDialog.resize(234, 334)
        self.gridLayout = QtWidgets.QGridLayout(AddNewWordDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(AddNewWordDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.new_word_textedit = QtWidgets.QLineEdit(AddNewWordDialog)
        self.new_word_textedit.setObjectName("new_word_textedit")
        self.gridLayout.addWidget(self.new_word_textedit, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(AddNewWordDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.language_list_view = QtWidgets.QListWidget(AddNewWordDialog)
        self.language_list_view.setObjectName("language_list_view")
        self.gridLayout.addWidget(self.language_list_view, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.confirm_button = QtWidgets.QPushButton(AddNewWordDialog)
        self.confirm_button.setObjectName("confirm_button")
        self.horizontalLayout.addWidget(self.confirm_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)

        self.retranslateUi(AddNewWordDialog)
        self.confirm_button.clicked.connect(AddNewWordDialog.confirmSelection) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddNewWordDialog)

    def retranslateUi(self, AddNewWordDialog):
        _translate = QtCore.QCoreApplication.translate
        AddNewWordDialog.setWindowTitle(_translate("AddNewWordDialog", "Add new word"))
        self.label.setText(_translate("AddNewWordDialog", "Word"))
        self.label_2.setText(_translate("AddNewWordDialog", "Languages (multiple possible)"))
        self.confirm_button.setText(_translate("AddNewWordDialog", "Confirm"))
