# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/qtDesigner/synthesisDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SynthesisDialog(object):
    def setupUi(self, SynthesisDialog):
        SynthesisDialog.setObjectName("SynthesisDialog")
        SynthesisDialog.resize(603, 311)
        self.gridLayout_2 = QtWidgets.QGridLayout(SynthesisDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(SynthesisDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.log_textedit = QtWidgets.QPlainTextEdit(SynthesisDialog)
        self.log_textedit.setAutoFillBackground(False)
        self.log_textedit.setReadOnly(True)
        self.log_textedit.setObjectName("log_textedit")
        self.gridLayout.addWidget(self.log_textedit, 1, 0, 1, 2)
        self.progress_bar = QtWidgets.QProgressBar(SynthesisDialog)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setTextVisible(True)
        self.progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.progress_bar.setInvertedAppearance(False)
        self.progress_bar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progress_bar.setObjectName("progress_bar")
        self.gridLayout.addWidget(self.progress_bar, 2, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ok_button = QtWidgets.QPushButton(SynthesisDialog)
        self.ok_button.setEnabled(False)
        self.ok_button.setMinimumSize(QtCore.QSize(75, 0))
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.close_button = QtWidgets.QPushButton(SynthesisDialog)
        self.close_button.setMinimumSize(QtCore.QSize(75, 0))
        self.close_button.setObjectName("close_button")
        self.horizontalLayout.addWidget(self.close_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(SynthesisDialog)
        self.close_button.clicked.connect(SynthesisDialog.reject) # type: ignore
        self.ok_button.clicked.connect(SynthesisDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SynthesisDialog)

    def retranslateUi(self, SynthesisDialog):
        _translate = QtCore.QCoreApplication.translate
        SynthesisDialog.setWindowTitle(_translate("SynthesisDialog", "Synthesis in progress"))
        self.label.setText(_translate("SynthesisDialog", "Log"))
        self.ok_button.setText(_translate("SynthesisDialog", "OK"))
        self.close_button.setText(_translate("SynthesisDialog", "Cancel"))
