# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/qtDesigner/voiceTestDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VoiceTestDialog(object):
    def setupUi(self, VoiceTestDialog):
        VoiceTestDialog.setObjectName("VoiceTestDialog")
        VoiceTestDialog.resize(445, 75)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VoiceTestDialog.sizePolicy().hasHeightForWidth())
        VoiceTestDialog.setSizePolicy(sizePolicy)
        VoiceTestDialog.setMaximumSize(QtCore.QSize(16777215, 75))
        self.gridLayout_2 = QtWidgets.QGridLayout(VoiceTestDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(VoiceTestDialog)
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.voice_details_placeholder = QtWidgets.QLabel(VoiceTestDialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(False)
        self.voice_details_placeholder.setFont(font)
        self.voice_details_placeholder.setObjectName("voice_details_placeholder")
        self.horizontalLayout_2.addWidget(self.voice_details_placeholder)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(VoiceTestDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.text_to_play_box = QtWidgets.QLineEdit(VoiceTestDialog)
        self.text_to_play_box.setObjectName("text_to_play_box")
        self.horizontalLayout.addWidget(self.text_to_play_box)
        self.play_button = QtWidgets.QPushButton(VoiceTestDialog)
        self.play_button.setMaximumSize(QtCore.QSize(50, 16777215))
        self.play_button.setObjectName("play_button")
        self.horizontalLayout.addWidget(self.play_button)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(VoiceTestDialog)
        self.play_button.clicked.connect(VoiceTestDialog.playVoice) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(VoiceTestDialog)

    def retranslateUi(self, VoiceTestDialog):
        _translate = QtCore.QCoreApplication.translate
        VoiceTestDialog.setWindowTitle(_translate("VoiceTestDialog", "Voice Test"))
        self.label.setText(_translate("VoiceTestDialog", "Voice:"))
        self.voice_details_placeholder.setText(_translate("VoiceTestDialog", "voice_details_placeholder"))
        self.label_2.setText(_translate("VoiceTestDialog", "Your Text"))
        self.play_button.setText(_translate("VoiceTestDialog", "Play"))
